# Generated by Django 4.2.9 on 2024-03-22 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institusi', '0003_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nama_vendor', models.CharField(max_length=200)),
                ('jenis_entitas', models.CharField(max_length=200)),
                ('bidang_usaha', models.CharField(max_length=200)),
                ('alamat', models.TextField()),
                ('kota_kantor', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('keterangan', models.TextField()),
                ('nomor_whatsapp', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('organisasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institusi.institusi')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Entitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nama_entitas', models.CharField(max_length=200)),
                ('panggilan_entitas', models.CharField(max_length=200)),
                ('tipe_entitas', models.CharField(choices=[('individu', 'Individu'), ('institusi', 'Institusi')], max_length=10)),
                ('penyebutan', models.CharField(choices=[('', ''), ('bapak', 'Bapak'), ('ibu', 'Ibu'), ('mas', 'Mas'), ('mbak', 'Mbak'), ('ustadz', 'Ustadz'), ('ustadzah', 'Ustadzah'), ('pt', 'PT'), ('cv', 'CV'), ('perusahaan', 'Perusahaan'), ('komunitas', 'Komunitas')], default='', max_length=200)),
                ('status_jamaah', models.CharField(blank=True, choices=[('jamaah_aktif', 'Jamaah Aktif'), ('jamaah_non_aktif', 'Jamaah Non Aktif'), ('non_jamaah', 'Non Jamaah')], max_length=200, null=True)),
                ('alamat', models.TextField()),
                ('wilayah_domisili', models.CharField(max_length=200)),
                ('kota_domisili', models.CharField(max_length=200)),
                ('nomor_whatsapp', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('is_panitia', models.BooleanField(default=False)),
                ('organisasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institusi.institusi')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
