# Generated by Django 4.2.9 on 2024-03-24 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entitas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entitas',
            name='penyebutan',
            field=models.CharField(choices=[('', ''), ('bapak', 'Bapak'), ('ibu', 'Ibu'), ('mas', 'Mas'), ('mbak', 'Mbak'), ('ustadz', 'Ustadz'), ('ustadzah', 'Ustadzah'), ('pt', 'PT'), ('cv', 'CV'), ('perusahaan', 'Perusahaan'), ('usaha', 'Usaha'), ('komunitas', 'Komunitas')], default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='entitas',
            name='tipe_entitas',
            field=models.CharField(choices=[('individu', 'Individu'), ('institusi', 'Institusi'), ('vendor', 'Vendor')], max_length=10),
        ),
        migrations.DeleteModel(
            name='Vendor',
        ),
    ]
