# Generated by Django 4.2.9 on 2024-03-24 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entitas', '0002_alter_entitas_penyebutan_alter_entitas_tipe_entitas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entitas',
            name='id_kencleng',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='entitas',
            name='id_tunai',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='entitas',
            name='is_donatur',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entitas',
            name='is_internal',
            field=models.BooleanField(default=False),
        ),
    ]
