# Generated by Django 4.2.9 on 2024-03-24 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entitas', '0004_alter_entitas_alamat_alter_entitas_kota_domisili_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entitas',
            name='penyebutan',
            field=models.CharField(blank=True, choices=[('', ''), ('pak', 'Pak'), ('bu', 'Bu'), ('sdr', 'Sdr'), ('ustadz', 'Ustadz'), ('ustadzah', 'Ustadzah'), ('pt', 'PT'), ('cv', 'CV'), ('perusahaan', 'Perusahaan'), ('usaha', 'Usaha'), ('komunitas', 'Komunitas')], default='', max_length=200, null=True),
        ),
    ]
