# Generated by Django 4.2.9 on 2024-03-22 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('program', '0003_alter_programkerja_keterangan'),
        ('institusi', '0003_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='KodeAkun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_akun', models.CharField(max_length=100)),
                ('nama_akun', models.CharField(max_length=100)),
                ('debet_or_kredit', models.CharField(choices=[('debet', 'Debet'), ('kredit', 'Kredit')], max_length=100)),
                ('kategori_pembukuan', models.CharField(choices=[('neraca', 'Neraca'), ('labarugi', 'Laba Rugi')], max_length=100)),
                ('catatan', models.TextField(blank=True, null=True)),
                ('institusi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institusi.institusi')),
                ('nama_program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='program.programkerja')),
                ('pasangan_akun', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lapkeuangan.kodeakun')),
            ],
        ),
    ]
