# Generated by Django 4.2.9 on 2024-03-22 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lapkeuangan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kodeakun',
            name='nama_program',
        ),
    ]
