# Generated by Django 4.2.9 on 2024-03-23 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entitas', '0001_initial'),
        ('institusi', '0003_unit'),
        ('lapkeuangan', '0002_remove_kodeakun_nama_program'),
    ]

    operations = [
        migrations.CreateModel(
            name='JurnalTransaksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nomer_transaksi', models.CharField(max_length=100)),
                ('urutan_per_kode_akun', models.IntegerField()),
                ('tanggal_transaksi', models.DateField()),
                ('keterangan', models.TextField()),
                ('jumlah', models.DecimalField(decimal_places=2, default=0.0, max_digits=25)),
                ('debet_or_kredit', models.CharField(choices=[('debet', 'Debet'), ('kredit', 'Kredit')], max_length=100)),
                ('nominal_debet', models.DecimalField(decimal_places=2, default=0.0, max_digits=25)),
                ('nominal_kredit', models.DecimalField(decimal_places=2, default=0.0, max_digits=25)),
                ('catatan', models.TextField(blank=True, null=True)),
                ('entitas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entitas_transaksi', to='entitas.entitas')),
                ('kode_akun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lapkeuangan.kodeakun')),
                ('organisasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institusi.institusi')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
