# Generated by Django 4.2.9 on 2024-03-24 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0007_programkerja_anggaran_agustus_and_more'),
        ('lapkeuangan', '0003_jurnaltransaksi'),
    ]

    operations = [
        migrations.AddField(
            model_name='jurnaltransaksi',
            name='program',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='program.programkerja'),
            preserve_default=False,
        ),
    ]
