# Generated by Django 4.2.9 on 2024-04-09 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lapkeuangan', '0004_jurnaltransaksi_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='jurnaltransaksi',
            name='nama_akun',
            field=models.CharField(default='akun', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jurnaltransaksi',
            name='no_bukti_transaksi',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jurnaltransaksi',
            name='urutan_transaksi',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
