# Generated by Django 4.2.9 on 2024-04-09 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lapkeuangan', '0005_jurnaltransaksi_nama_akun_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jurnaltransaksi',
            name='urutan_per_kode_akun',
        ),
    ]
