# Generated by Django 4.2.9 on 2024-04-10 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lapkeuangan', '0006_remove_jurnaltransaksi_urutan_per_kode_akun'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jurnaltransaksi',
            name='keterangan',
        ),
    ]
