# Generated by Django 4.2.9 on 2024-04-10 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lapkeuangan', '0007_remove_jurnaltransaksi_keterangan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jurnaltransaksi',
            name='debet_or_kredit',
        ),
        migrations.RemoveField(
            model_name='jurnaltransaksi',
            name='jumlah',
        ),
    ]
