# Generated by Django 4.2.9 on 2024-04-10 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lapkeuangan', '0008_remove_jurnaltransaksi_debet_or_kredit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jurnaltransaksi',
            name='keterangan_transaksi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
