# Generated by Django 4.2.9 on 2024-04-12 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institusi', '0003_unit'),
        ('entitas', '0006_alter_entitas_penyebutan'),
        ('program', '0007_programkerja_anggaran_agustus_and_more'),
        ('lapkeuangan', '0009_jurnaltransaksi_keterangan_transaksi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jurnaltransaksi',
            old_name='nama_akun',
            new_name='akun_nama',
        ),
        migrations.RemoveField(
            model_name='jurnaltransaksi',
            name='entitas',
        ),
        migrations.RemoveField(
            model_name='jurnaltransaksi',
            name='kode_akun',
        ),
        migrations.RemoveField(
            model_name='jurnaltransaksi',
            name='program',
        ),
        migrations.AddField(
            model_name='jurnaltransaksi',
            name='akun_kode',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='jurnaltransaksi_akun_kode', to='lapkeuangan.kodeakun'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jurnaltransaksi',
            name='entitas_id',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='jurnaltransaksi_entitas_transaksi', to='entitas.entitas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jurnaltransaksi',
            name='entitas_nama',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jurnaltransaksi',
            name='program_id',
            field=models.ForeignKey(default=347, on_delete=django.db.models.deletion.CASCADE, related_name='jurnaltransaksi_program', to='program.programkerja'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jurnaltransaksi',
            name='program_nama',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jurnaltransaksi',
            name='unitowner_id',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, related_name='jurnaltransaksi_unit_owner', to='institusi.unit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jurnaltransaksi',
            name='unitowner_nama',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
