# Generated by Django 4.2.9 on 2024-03-22 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institusi', '0003_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramKerja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kode_program', models.CharField(max_length=100)),
                ('nama_program', models.CharField(max_length=100)),
                ('jenis_input_output', models.CharField(choices=[('TER', 'Input Terikat'), ('BEB', 'Input TakTerikat'), ('OUT', 'Output')], default='OUT', max_length=3)),
                ('jenis_program', models.CharField(choices=[('nonAsset', 'Non Asset'), ('yesAsset', 'Asset')], default='nonAsset', max_length=8)),
                ('sifat_kreasi', models.CharField(choices=[('terencana', 'Terencana'), ('modifikasi', 'Modifikasi'), ('usulanbaru', 'Usulan Baru'), ('dipertimbangkan', 'Dipertimbangkan'), ('usulanditolak', 'Usulan Ditolak'), ('digugurkan', 'Digugurkan')], default='terencana', max_length=15)),
                ('periode_anggaran', models.CharField(choices=[('bulan', 'Bulan'), ('tahun', 'Tahun')], default='bulan', max_length=5)),
                ('sifat_periode_anggaran', models.CharField(choices=[('fiks', 'Fiks'), ('fleksibel', 'Fleksibel')], default='fiks', max_length=9)),
                ('anggaran_terencana', models.DecimalField(decimal_places=2, default=0.0, max_digits=25)),
                ('anggaran_realisasi', models.DecimalField(decimal_places=2, default=0.0, max_digits=25)),
                ('anggaran_selisih', models.DecimalField(decimal_places=2, default=0.0, max_digits=25)),
                ('keterangan', models.TextField()),
                ('owner_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institusi.unit')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
