# Generated by Django 4.2.9 on 2024-03-22 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0002_anggaranprogram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programkerja',
            name='keterangan',
            field=models.TextField(blank=True, null=True),
        ),
    ]
