# Generated by Django 4.2.9 on 2024-03-23 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0004_alter_programkerja_jenis_input_output'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programkerja',
            name='anggaran_terencana',
        ),
        migrations.AddField(
            model_name='programkerja',
            name='kode_akun',
            field=models.CharField(default='text', max_length=20),
            preserve_default=False,
        ),
    ]
