# Generated by Django 4.2.9 on 2024-03-23 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0005_remove_programkerja_anggaran_terencana_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programkerja',
            name='anggaran_realisasi',
        ),
        migrations.RemoveField(
            model_name='programkerja',
            name='anggaran_selisih',
        ),
    ]
