# Generated by Django 4.2.9 on 2024-03-23 04:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0006_remove_programkerja_anggaran_realisasi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programkerja',
            name='anggaran_agustus',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=25, null=True),
        ),
        migrations.AddField(
            model_name='programkerja',
            name='anggaran_april',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=25, null=True),
        ),
        migrations.AddField(
            model_name='programkerja',
            name='anggaran_desember',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=25, null=True),
        ),
        migrations.AddField(
            model_name='programkerja',
            name='anggaran_februari',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=25, null=True),
        ),
        migrations.AddField(
            model_name='programkerja',
            name='anggaran_januari',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=25, null=True),
        ),
        migrations.AddField(
            model_name='programkerja',
            name='anggaran_juli',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=25, null=True),
        ),
        migrations.AddField(
            model_name='programkerja',
            name='anggaran_juni',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=25, null=True),
        ),
        migrations.AddField(
            model_name='programkerja',
            name='anggaran_maret',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=25, null=True),
        ),
        migrations.AddField(
            model_name='programkerja',
            name='anggaran_mei',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=25, null=True),
        ),
        migrations.AddField(
            model_name='programkerja',
            name='anggaran_november',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=25, null=True),
        ),
        migrations.AddField(
            model_name='programkerja',
            name='anggaran_oktober',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=25, null=True),
        ),
        migrations.AddField(
            model_name='programkerja',
            name='anggaran_september',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=25, null=True),
        ),
        migrations.AddField(
            model_name='programkerja',
            name='tahun_anggaran',
            field=models.IntegerField(default=2024, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(9999)]),
        ),
        migrations.DeleteModel(
            name='AnggaranProgram',
        ),
    ]
