# Generated by Django 4.2.9 on 2024-03-22 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institusi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_institusi', models.CharField(max_length=200)),
                ('julukan_institusi', models.CharField(max_length=50)),
                ('alamat', models.TextField()),
                ('wilayah', models.CharField(max_length=200)),
                ('kota', models.CharField(max_length=200)),
                ('nomorWA', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
