# Generated by Django 4.2.9 on 2024-03-22 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institusi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bidang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namaBidang', models.CharField(max_length=200)),
                ('kodeBidang', models.CharField(max_length=10, null=True)),
                ('organisasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institusi.institusi')),
            ],
        ),
    ]
