# Generated by Django 4.2.9 on 2024-03-22 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institusi', '0002_bidang'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namaUnit', models.CharField(max_length=200)),
                ('kodeUnit', models.CharField(max_length=10)),
                ('bidang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institusi.bidang')),
            ],
        ),
    ]
