# Generated by Django 4.2.9 on 2024-03-26 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nipd', models.CharField(max_length=20)),
                ('nisn', models.CharField(max_length=20)),
                ('nik', models.CharField(max_length=16)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('birth_place', models.CharField(max_length=50)),
                ('birth_date', models.DateField()),
                ('religion', models.CharField(default='Islam', max_length=30)),
                ('address', models.TextField()),
                ('rt', models.CharField(max_length=3)),
                ('rw', models.CharField(max_length=3)),
                ('village', models.CharField(max_length=50)),
                ('sub_district', models.CharField(max_length=50)),
                ('postal_code', models.CharField(max_length=5)),
                ('living_with', models.CharField(choices=[('ortu', 'Bersama orang tua'), ('wali', 'Bersama wali')], max_length=10)),
                ('transportation', models.CharField(choices=[('sepedamotor', 'Sepeda motor'), ('mobil', 'Mobil pribadi'), ('jalan', 'Jalan kaki')], max_length=20)),
                ('current_class', models.CharField(max_length=50)),
                ('national_exam_number', models.CharField(max_length=20)),
                ('diploma_number', models.CharField(max_length=20)),
                ('birth_certificate_number', models.CharField(max_length=20)),
                ('bank', models.CharField(max_length=50)),
                ('bank_account_number', models.CharField(max_length=20)),
                ('account_holder_name', models.CharField(max_length=100)),
                ('previous_school', models.CharField(max_length=100)),
                ('child_order', models.IntegerField()),
                ('family_card_number', models.CharField(max_length=20)),
                ('weight', models.IntegerField()),
                ('height', models.IntegerField()),
                ('head_circumference', models.IntegerField()),
                ('siblings_count', models.IntegerField()),
                ('distance_to_school', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=50)),
                ('payment_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_type', models.CharField(choices=[('PMB', 'Biaya Penerimaan Murid Baru'), ('DUL', 'Biaya Daftar Ulang'), ('SPP', 'Sumbangan Pembinaan Pendidikan')], max_length=3)),
                ('class_name', models.CharField(max_length=50)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kbtkadmin.student')),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birth_year', models.IntegerField()),
                ('education_level', models.CharField(choices=[('noschooling', 'Tidak sekolah'), ('smp', 'SMP/sederajat'), ('sma', 'SMA/sederajat'), ('diploma', 'D3'), ('sarjana', 'S1'), ('master', 'S2'), ('doktor', 'S3')], max_length=20)),
                ('job', models.CharField(choices=[('swasta', 'Karyawan Swasta'), ('tentara', 'TNI/Polri'), ('pengusaha', 'Wiraswasta'), ('lainnya', 'Lainnya'), ('pns', 'Karyawan BUMN')], max_length=50)),
                ('income', models.CharField(choices=[('<2M', 'kurang dari Rp. 2,000,000'), ('2M-5M', 'Rp. 2,000,000 - Rp. 4,999,999'), ('5M-20M', 'Rp. 5,000,000 - Rp. 20,000,000'), ('>20M', 'di atas Rp. 20,000,000')], max_length=6)),
                ('nik', models.CharField(max_length=16)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kbtkadmin.student')),
            ],
        ),
        migrations.CreateModel(
            name='InstallmentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_date', models.DateField()),
                ('installment_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('remaining_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='kbtkadmin.payment')),
            ],
        ),
    ]
